tools:
    external_code_coverage: false
    php_code_sniffer: true
    php_sim: true
    php_changetracking: true
    php_cs_fixer: true
    php_mess_detector: true
    php_pdepend: true
    php_analyzer: true
    sensiolabs_security_checker: true
filter:
    excluded_paths:
        - Tests/*
